### ISSUE TITLE
在 Mac OSX Sierra 10.12.5 运行出现：

### ISSUE THREAD

**Issue by arkilis** [callmewhy/financial-calculator#1]
![image](https://user-images.githubusercontent.com/1528028/28251638-e01f2bb2-6ac4-11e7-8550-156c8233e784.png)

**Comment by callmewhy** [comment]
似乎是升级系统了？参考：https://github.com/sass/node-sass/issues/1764

rebuild 试试：
```
npm rebuild node-sass
```
